language: go

go:
  - 1.12.x
  - 1.13.x
  - tip

before_install:
  - go get -t -d -v .

script:
  - go test -v . -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  allow_failures:
    - go: tip
